ALTER TABLE QGames
ADD score2 INTEGER;

ALTER TABLE QPlayers
ALTER COLUMN beginDate TYPE INTEGER 
USING (CASE WHEN beginDate IS NULL THEN NULL ELSE to_char(beginDate, 'YYYYMMDD')::INTEGER END);

ALTER TABLE QPlayers
ALTER COLUMN endDate TYPE INTEGER 
USING (CASE WHEN endDate IS NULL THEN NULL ELSE to_char(endDate, 'YYYYMMDD')::INTEGER END);